export const roles = [
  "Attending Physician",
  "Infectious Disease Specialist",
  "Clinical Pharmacist",
  "Stewardship Admin",
];

export const patients = [
  {
    id: "P-2024-00125",
    mrn: "12345678",
    name: "James Wilson",
    ageSex: "68 / M",
    ward: "ICU",
    bed: "12B",
    diagnosis: "Ventilator-associated pneumonia",
    infectionType: "Pneumonia",
    therapy: "Piperacillin/Tazobactam",
    status: "Safe to continue",
    confidence: 90,
    allergies: "Penicillin (rash)",
    admitted: "May 6, 2024",
    daysAdmitted: 7,
    attending: "Dr. Sarah Johnson",
    temp: "37.8 °C",
    hr: "92",
    bp: "116/68",
    rr: "20",
    spo2: "95%",
    reviewStatus: "safe",
    lastUpdated: "May 13, 09:15",
    currentProblems: ["Ventilator-associated pneumonia (active)", "Septic shock - improving", "Type 2 diabetes mellitus"],
    cultures: [
      ["Endotracheal aspirate", "Moderate growth", "Pseudomonas aeruginosa", "May 7, 2024", "Final"],
      ["Blood culture (x2)", "No growth", "-", "May 6, 2024", "Final"],
      ["Urine culture", "No growth", "-", "May 6, 2024", "Final"],
    ],
    medications: [
      ["Piperacillin/Tazobactam", "4.5 g IV", "q6h", "VAP", "May 10, 2024"],
      ["Vancomycin", "1 g IV", "q12h", "Empiric", "May 10, 2024"],
      ["Norepinephrine", "-", "Continuous", "Septic shock", "May 6, 2024"],
      ["Acetaminophen", "650 mg PO", "q6h PRN", "Fever", "May 6, 2024"],
    ],
    labs: [
      ["WBC", "12.6 x10³/µL", "4.0 - 11.0", "May 13"],
      ["Procalcitonin", "0.82 ng/mL", "< 0.10", "May 13"],
      ["Creatinine", "1.2 mg/dL", "0.6 - 1.2", "May 13"],
      ["CRP", "112 mg/L", "< 10", "May 13"],
    ],
    timeline: [
      ["May 6 08:10", "Admission to ICU", "Septic shock, intubated. Empiric antibiotics started."],
      ["May 6 08:30", "Blood cultures collected", "x2 sets"],
      ["May 7 10:20", "Endotracheal aspirate collected", "Culture sent"],
      ["May 10 09:15", "Antibiotics escalated", "Started Piperacillin/Tazobactam + Vancomycin"],
      ["May 13 08:30", "AMS Review checkpoint", "Pending review"],
    ],
  },
  {
    id: "P-2024-00118",
    mrn: "22450118",
    name: "Maria Gonzalez",
    ageSex: "72 / F",
    ward: "Med Ward",
    bed: "8A",
    diagnosis: "Urinary tract infection",
    infectionType: "UTI",
    therapy: "Ceftriaxone",
    status: "Consider de-escalation",
    confidence: 72,
    allergies: "No known drug allergies",
    admitted: "May 9, 2024",
    daysAdmitted: 4,
    attending: "Dr. Priya Patel",
    temp: "37.1 °C",
    hr: "84",
    bp: "128/74",
    rr: "18",
    spo2: "98%",
    reviewStatus: "switch",
    lastUpdated: "May 13, 08:47",
    currentProblems: ["Complicated urinary tract infection", "Chronic kidney disease stage 3"],
    cultures: [["Urine culture", "Positive", "Enterobacter cloacae", "May 10, 2024", "Prelim"]],
    medications: [["Ceftriaxone", "1 g IV", "q24h", "UTI", "May 9, 2024"]],
    labs: [["WBC", "9.8 x10³/µL", "4.0 - 11.0", "May 13"], ["Creatinine", "1.5 mg/dL", "0.6 - 1.2", "May 13"]],
    timeline: [["May 9 12:10", "Admitted", "Fever and dysuria"], ["May 10 09:00", "Culture collected", "Urine specimen sent"]],
  },
  {
    id: "P-2024-00107",
    mrn: "3400107",
    name: "Robert Chen",
    ageSex: "58 / M",
    ward: "ICU",
    bed: "7C",
    diagnosis: "Bloodstream infection",
    infectionType: "BSI",
    therapy: "Meropenem",
    status: "Needs review",
    confidence: 48,
    allergies: "No known drug allergies",
    admitted: "May 11, 2024",
    daysAdmitted: 2,
    attending: "Dr. James Lee",
    temp: "38.6 °C",
    hr: "108",
    bp: "102/64",
    rr: "24",
    spo2: "94%",
    reviewStatus: "review",
    lastUpdated: "May 13, 07:59",
    currentProblems: ["Bloodstream infection", "Central line present"],
    cultures: [["Blood culture", "Gram-negative bacilli", "Pending ID", "May 12, 2024", "Pending"]],
    medications: [["Meropenem", "1 g IV", "q8h", "BSI", "May 12, 2024"]],
    labs: [["WBC", "15.2 x10³/µL", "4.0 - 11.0", "May 13"], ["Creatinine", "1.0 mg/dL", "0.6 - 1.2", "May 13"]],
    timeline: [["May 11 21:00", "Admitted", "Fever and hypotension"], ["May 12 08:20", "Meropenem started", "Broad-spectrum coverage"]],
  },
  {
    id: "P-2024-00098",
    mrn: "98440098",
    name: "Linda Patel",
    ageSex: "65 / F",
    ward: "Surg Ward",
    bed: "21",
    diagnosis: "Intra-abdominal infection",
    infectionType: "Abdominal",
    therapy: "Meropenem",
    status: "Safe to continue",
    confidence: 88,
    allergies: "No known drug allergies",
    admitted: "May 8, 2024",
    daysAdmitted: 5,
    attending: "Dr. Michael Anderson",
    temp: "37.4 °C",
    hr: "88",
    bp: "122/70",
    rr: "17",
    spo2: "97%",
    reviewStatus: "safe",
    lastUpdated: "May 13, 07:32",
    currentProblems: ["Post-operative intra-abdominal infection"],
    cultures: [["Abdominal fluid", "Mixed flora", "Pending", "May 9, 2024", "Pending"]],
    medications: [["Meropenem", "1 g IV", "q8h", "Abdominal infection", "May 8, 2024"]],
    labs: [["WBC", "10.9 x10³/µL", "4.0 - 11.0", "May 13"]],
    timeline: [["May 8 14:00", "Surgery completed", "Source control achieved"]],
  },
  {
    id: "P-2024-00075",
    mrn: "75000075",
    name: "Susan Lee",
    ageSex: "77 / F",
    ward: "Med Ward",
    bed: "14D",
    diagnosis: "Pneumonia",
    infectionType: "Pneumonia",
    therapy: "Cefepime",
    status: "Escalated",
    confidence: 35,
    allergies: "Penicillin (hives)",
    admitted: "May 6, 2024",
    daysAdmitted: 7,
    attending: "Dr. James Lee",
    temp: "38.2 °C",
    hr: "96",
    bp: "118/70",
    rr: "22",
    spo2: "92%",
    reviewStatus: "escalated",
    lastUpdated: "May 12, 17:05",
    currentProblems: ["Pneumonia", "Missing culture result"],
    cultures: [["Respiratory culture", "Pending", "-", "May 12, 2024", "Pending"]],
    medications: [["Cefepime", "2 g IV", "q8h", "Pneumonia", "May 11, 2024"]],
    labs: [["WBC", "13.4 x10³/µL", "4.0 - 11.0", "May 13"]],
    timeline: [["May 12 17:05", "Escalated", "Specialist review requested"]],
  },
  {
    id: "P-2024-00062",
    mrn: "62000062",
    name: "David Martinez",
    ageSex: "54 / M",
    ward: "ICU",
    bed: "3A",
    diagnosis: "Central line-associated BSI",
    infectionType: "BSI",
    therapy: "Vancomycin, Cefepime",
    status: "Needs review",
    confidence: 42,
    allergies: "No known drug allergies",
    admitted: "May 10, 2024",
    daysAdmitted: 3,
    attending: "Dr. Priya Patel",
    temp: "38.0 °C",
    hr: "101",
    bp: "110/66",
    rr: "21",
    spo2: "96%",
    reviewStatus: "review",
    lastUpdated: "May 12, 16:41",
    currentProblems: ["Central line-associated bloodstream infection"],
    cultures: [["Blood culture", "Gram-positive cocci", "Pending", "May 12, 2024", "Pending"]],
    medications: [["Vancomycin", "1 g IV", "q12h", "BSI", "May 12, 2024"], ["Cefepime", "2 g IV", "q8h", "BSI", "May 12, 2024"]],
    labs: [["Creatinine", "1.8 mg/dL", "0.6 - 1.2", "May 13"]],
    timeline: [["May 12 16:41", "Review flagged", "Renal dosing check required"]],
  },
  {
    id: "P-2024-00031",
    mrn: "31000031",
    name: "Emily Davis",
    ageSex: "45 / F",
    ward: "Med Ward",
    bed: "10C",
    diagnosis: "Pyelonephritis",
    infectionType: "UTI",
    therapy: "Ceftriaxone",
    status: "Safe to continue",
    confidence: 85,
    allergies: "Sulfa allergy",
    admitted: "May 12, 2024",
    daysAdmitted: 1,
    attending: "Dr. Michael Anderson",
    temp: "37.6 °C",
    hr: "90",
    bp: "121/78",
    rr: "16",
    spo2: "99%",
    reviewStatus: "safe",
    lastUpdated: "May 12, 13:55",
    currentProblems: ["Pyelonephritis"],
    cultures: [["Urine culture", "Pending", "-", "May 12, 2024", "Pending"]],
    medications: [["Ceftriaxone", "1 g IV", "q24h", "Pyelonephritis", "May 12, 2024"]],
    labs: [["WBC", "11.7 x10³/µL", "4.0 - 11.0", "May 13"]],
    timeline: [["May 12 13:55", "AMS review", "Antibiotic choice reviewed"]],
  },
];

export const recommendations = [
  {
    id: "REC-2024-00125-01",
    patientId: "P-2024-00125",
    current: { antimicrobial: "Piperacillin/Tazobactam", dose: "4.5 g", route: "IV", frequency: "Every 6 hours", duration: "7 days", start: "May 11, 2024" },
    suggested: { antimicrobial: "Meropenem", dose: "1 g", route: "IV", frequency: "Every 8 hours", duration: "7 days" },
    status: "Recommended",
    confidence: 88,
    rationale: ["Culture shows Gram-negative bacilli resistant to piperacillin/tazobactam", "Meropenem is active based on local antibiogram", "Better pulmonary penetration for suspected VAP", "Aligns with IDSA/ATS VAP guidance"],
    safety: ["No known drug allergies", "No history of severe antibiotic reactions", "No C. difficile risk factors identified", "Appropriate for site of infection"],
    interaction: "Valproic acid: Meropenem may reduce valproic acid levels. Monitor clinical response.",
    renal: "eGFR: 48 mL/min/1.73m². Recommended dose appropriate for current renal function.",
  },
  {
    id: "REC-2024-00118-01",
    patientId: "P-2024-00118",
    current: { antimicrobial: "Ceftriaxone", dose: "1 g", route: "IV", frequency: "Every 24 hours", duration: "5 days", start: "May 9, 2024" },
    suggested: { antimicrobial: "Cefazolin", dose: "1 g", route: "IV", frequency: "Every 8 hours", duration: "5 days" },
    status: "Consider de-escalation",
    confidence: 72,
    rationale: ["Clinical response is stable", "Narrower therapy is appropriate when cultures finalize", "Renal function supports dose adjustment"],
    safety: ["No documented beta-lactam allergy", "Renal function monitored"],
    interaction: "No major drug interactions identified.",
    renal: "Use renal-adjusted dosing if creatinine rises.",
  },
  {
    id: "REC-2024-00107-01",
    patientId: "P-2024-00107",
    current: { antimicrobial: "Meropenem", dose: "1 g", route: "IV", frequency: "Every 8 hours", duration: "TBD", start: "May 12, 2024" },
    suggested: { antimicrobial: "Continue current therapy", dose: "1 g", route: "IV", frequency: "Every 8 hours", duration: "Reassess at 48h" },
    status: "Needs review",
    confidence: 48,
    rationale: ["Low confidence due to pending culture ID", "Severe infection and conflicting clinical findings"],
    safety: ["No allergy conflict found", "Monitor renal function"],
    interaction: "No major interactions identified.",
    renal: "Renal function currently stable.",
  },
];

export const reviews = [
  { id: "REV-2024-00125", patientId: "P-2024-00125", priority: "High", reviewer: "Dr. Michael Anderson", due: "Today 10:00 AM", status: "Pending review", reason: "High antibiotic use", confidence: 90 },
  { id: "REV-2024-00118", patientId: "P-2024-00118", priority: "Moderate", reviewer: "Dr. Priya Patel", due: "Today 11:00 AM", status: "In progress", reason: "De-escalation opportunity", confidence: 72 },
  { id: "REV-2024-00107", patientId: "P-2024-00107", priority: "High", reviewer: "Dr. James Lee", due: "Today 01:00 PM", status: "Pending review", reason: "High-risk antibiotic", confidence: 48 },
  { id: "REV-2024-00075", patientId: "P-2024-00075", priority: "High", reviewer: "Dr. Sarah Johnson", due: "Tomorrow 09:00 AM", status: "Escalated", reason: "Duration review", confidence: 35 },
  { id: "REV-2024-00062", patientId: "P-2024-00062", priority: "Moderate", reviewer: "Dr. Priya Patel", due: "Tomorrow 10:00 AM", status: "Pending review", reason: "High-risk antibiotic", confidence: 42 },
  { id: "REV-2024-00031", patientId: "P-2024-00031", priority: "Moderate", reviewer: "Dr. Michael Anderson", due: "May 15 09:00 AM", status: "Pending review", reason: "Antibiotic allergy", confidence: 85 },
];

export const alerts = [
  { id: "A-001", type: "Allergy Alert", patientId: "P-2024-00125", detail: "Penicillin ordered despite documented allergy.", priority: "Critical", time: "10 min ago", category: "Critical" },
  { id: "A-002", type: "Low-Confidence Recommendation", patientId: "P-2024-00107", detail: "Recommendation confidence 48% below threshold.", priority: "High", time: "18 min ago", category: "Recommendation Updates" },
  { id: "A-003", type: "New Culture Result Available", patientId: "P-2024-00118", detail: "Blood culture growing Enterobacter cloacae.", priority: "High", time: "25 min ago", category: "Culture Updates" },
  { id: "A-004", type: "Review Overdue", patientId: "P-2024-00075", detail: "Escalation review overdue by 1 day.", priority: "High", time: "1 hr ago", category: "Review Deadlines" },
  { id: "A-005", type: "Duplicate Therapy Concern", patientId: "P-2024-00062", detail: "Meropenem + Piperacillin/Tazobactam overlap detected.", priority: "Moderate", time: "2 hrs ago", category: "Critical" },
  { id: "A-006", type: "Escalation Assigned", patientId: "P-2024-00031", detail: "Assigned to Dr. Michael Anderson.", priority: "Low", time: "3 hrs ago", category: "Review Deadlines" },
];

export const reports = [
  ["Case Summary Report", "May 7, 2024 - May 13, 2024", "May 13, 2024 10:24 AM", "Dr. Sarah Johnson", "PDF", "842 KB"],
  ["Daily Review Report", "May 12, 2024", "May 12, 2024 06:15 PM", "Dr. Michael Chen", "PDF", "512 KB"],
  ["Ward Antimicrobial Use", "Apr 28, 2024 - May 4, 2024", "May 5, 2024 09:02 AM", "Dr. Sarah Johnson", "CSV", "198 KB"],
  ["Monthly Stewardship Report", "April 2024", "May 1, 2024 08:45 AM", "Dr. Sarah Johnson", "PDF", "1.2 MB"],
];
